### ISSUE TITLE
bug: mathlib already contains `LazyList.filter._cstage1`

### ISSUE THREAD

**Issue by joneugster** [leanprover-community/duper#4]
Using [`DuperDemo`](https://github.com/JOSHCLUNE/DuperDemo/tree/main) and adding `import Mathlib` results in the following error:

```
import Mathlib.Data.LazyList failed, environment already
  contains 'LazyList.filter._cstage1' from Duper.Util.LazyList
```

(This uses duper `v0.0.3` and the corresponding mathlib as in DuperDemo commit [`1d43df3`](https://github.com/JOSHCLUNE/DuperDemo/commit/1d43df36180628661e25b6ab1e60e4ea5d580bbe))

**Comment by JOSHCLUNE** [comment]
Thanks for reporting this. The name clash is now resolved in v0.0.4.
